name: epgstation-build-1.7.4-debian

on: [ workflow_dispatch ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Buildx (build) - 1.7.4-debian
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --tag collelog/epgstation-build:1.7.4-debian \
            --file ./epgstation-build/1.7.4-debian.Dockerfile ./epgstation-build/ \
            --ulimit 2048
      -
        name: Docker Buildx (push) - 1.7.4-debian
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag collelog/epgstation-build:1.7.4-debian \
            --file ./epgstation-build/1.7.4-debian.Dockerfile ./epgstation-build/
      -
        name: Docker Check Manifest - 1.7.4-debian
        run: |
          docker run --rm mplatform/mquery collelog/epgstation-build:1.7.4-debian
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
