name: epgstation-build-latest_child2

on:
  workflow_run:
    workflows:
      - epgstation-build-latest_child1
    types:
      - completed

jobs:
  buildx:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      -
        name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          df -h
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Setup kernel for react native, increase watchers
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push - latest-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./epgstation-build/
          file: ./epgstation-build/latest-alpine.Dockerfile
          tags: |
            collelog/epgstation-build:latest-alpine
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
