name: mirakc-master-alpine

on: [ workflow_dispatch ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --tag collelog/mirakc:master-alpine \
            --file ./mirakc/master-alpine.Dockerfile ./mirakc/
      -
        name: Docker Buildx (push)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag collelog/mirakc:master-alpine \
            --file ./mirakc/master-alpine.Dockerfile ./mirakc/
      -
        name: Docker Check Manifest
        run: |
          docker run --rm mplatform/mquery collelog/mirakc:master-alpine
      -
        name: Docker Buildx (build) - master-alpine-amd64
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64 \
            --output "type=image,push=false" \
            --tag collelog/mirakc:master-alpine-amd64 \
            --file ./mirakc/master-alpine-amd64.Dockerfile ./mirakc/
      -
        name: Docker Buildx (push) - master-alpine-amd64
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64 \
            --output "type=image,push=true" \
            --tag collelog/mirakc:master-alpine-amd64 \
            --file ./mirakc/master-alpine-amd64.Dockerfile ./mirakc/
      -
        name: Docker Check Manifest - master-alpine-amd64
        run: |
          docker run --rm mplatform/mquery collelog/mirakc:master-alpine-amd64
      -
        name: Docker Buildx (build) - master-alpine-rpi4-64
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/arm64 \
            --output "type=image,push=false" \
            --tag collelog/mirakc:master-alpine-rpi4-64 \
            --file ./mirakc/master-alpine-rpi4-64.Dockerfile ./mirakc/
      -
        name: Docker Buildx (push) - master-alpine-rpi4-64
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/arm64 \
            --output "type=image,push=true" \
            --tag collelog/mirakc:master-alpine-rpi4-64 \
            --file ./mirakc/master-alpine-rpi4-64.Dockerfile ./mirakc/
      -
        name: Docker Check Manifest - master-alpine-rpi4-64
        run: |
          docker run --rm mplatform/mquery collelog/mirakc:master-alpine-rpi4-64
      -
        name: Docker Buildx (build) - master-alpine-rpi4-32
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/arm/v7 \
            --output "type=image,push=false" \
            --tag collelog/mirakc:master-alpine-rpi4-32 \
            --file ./mirakc/master-alpine-rpi4-32.Dockerfile ./mirakc/
      -
        name: Docker Buildx (push) - master-alpine-rpi4-32
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --tag collelog/mirakc:master-alpine-rpi4-32 \
            --file ./mirakc/master-alpine-rpi4-32.Dockerfile ./mirakc/
      -
        name: Docker Check Manifest - master-alpine-rpi4-32
        run: |
          docker run --rm mplatform/mquery collelog/mirakc:master-alpine-rpi4-32
      -
        name: Docker Buildx (build) - master-alpine-rpi3
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/arm/v7 \
            --output "type=image,push=false" \
            --tag collelog/mirakc:master-alpine-rpi3 \
            --file ./mirakc/master-alpine-rpi3.Dockerfile ./mirakc/
      -
        name: Docker Buildx (push) - master-alpine-rpi3
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/arm/v7 \
            --output "type=image,push=true" \
            --tag collelog/mirakc:master-alpine-rpi3 \
            --file ./mirakc/master-alpine-rpi3.Dockerfile ./mirakc/
      -
        name: Docker Check Manifest - master-alpine-rpi3
        run: |
          docker run --rm mplatform/mquery collelog/mirakc:master-alpine-rpi3
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
