name: recdvb-build-latest_child1

on:
  workflow_run:
    workflows:
      - recdvb-build-latest
    types:
      - completed

jobs:
  buildx:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push - sat-latest-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/sat-latest-alpine.Dockerfile
          tags: collelog/recdvb-build:sat-latest-alpine
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - sat-latest-alpine-amd64
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/sat-latest-alpine-amd64.Dockerfile
          tags: collelog/recdvb-build:sat-latest-alpine-amd64
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - sat-latest-alpine-rpi4-64
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/sat-latest-alpine-rpi4.Dockerfile
          tags: collelog/recdvb-build:sat-latest-alpine-rpi4-64
          platforms: linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - sat-latest-alpine-rpi4-32
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/sat-latest-alpine-rpi4.Dockerfile
          tags: collelog/recdvb-build:sat-latest-alpine-rpi4-32
          platforms: linux/arm/v7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - sat-latest-alpine-rpi3
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/sat-latest-alpine-rpi3.Dockerfile
          tags: collelog/recdvb-build:sat-latest-alpine-rpi3
          platforms: linux/arm/v7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - kaikoma-soft-latest-alpine
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/kaikoma-soft-latest-alpine.Dockerfile
          tags: collelog/recdvb-build:kaikoma-soft-latest-alpine
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - kaikoma-soft-latest-alpine-amd64
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/kaikoma-soft-latest-alpine-amd64.Dockerfile
          tags: collelog/recdvb-build:kaikoma-soft-latest-alpine-amd64
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - kaikoma-soft-latest-alpine-rpi4-64
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/kaikoma-soft-latest-alpine-rpi4.Dockerfile
          tags: collelog/recdvb-build:kaikoma-soft-latest-alpine-rpi4-64
          platforms: linux/arm64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - kaikoma-soft-latest-alpine-rpi4-32
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/kaikoma-soft-latest-alpine-rpi4.Dockerfile
          tags: collelog/recdvb-build:kaikoma-soft-latest-alpine-rpi4-32
          platforms: linux/arm/v7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      -
        name: Build and push - kaikoma-soft-latest-alpine-rpi3
        uses: docker/build-push-action@v2
        with:
          context: ./recdvb-build/
          file: ./recdvb-build/kaikoma-soft-latest-alpine-rpi3.Dockerfile
          tags: collelog/recdvb-build:kaikoma-soft-latest-alpine-rpi3
          platforms: linux/arm/v7
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
